name: validation
on: push
jobs:
  f_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          echo -e "Making sure all unit tests will run. There should be no \"fdescribe\" or \"fit\"."
          lib_dir="projects/mmm-toast/src/lib"
          fdescribe_found=$(grep -r "fdescribe" "${lib_dir}")
          fit_found=$(grep -r "fdescribe" "${lib_dir}")
          if [ -n "$FDESCRIBE" ]; then
            echo "fdescribe found"
            echo "$FDESCRIBE"
            exit 1
          fi
          if [ -n "$FIT" ]; then
              echo "fit found"
              echo "$FIT"
              exit 1
          fi
